-- Iniciativa Ofertas (adelanto de backend, sin superficie de cliente):
-- Business (comercio que publica ofertas) + Offer, con cola de aprobación
-- draft -> active/rejected y expiración automática (Historia 3.1/3.4 del
-- roadmap; ver FIXY_OFERTAS_INGESTA_DESIGN.md).
--
-- Igual que V2/V3/V4: válida para PostgreSQL (prod, flyway ON) y compatible
-- con H2 en modo PostgreSQL; en dev/test flyway está OFF y ddl-auto=update
-- cubre las entidades JPA — esta migración no corre ahí pero se mantiene
-- sincronizada.

CREATE TABLE businesses (
    id bigint NOT NULL,
    name varchar(255) NOT NULL,
    whatsapp_number varchar(255) NOT NULL,
    category varchar(255) NOT NULL,
    primary_zone varchar(255),
    status varchar(20) NOT NULL,
    provider_id bigint,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT businesses_pkey PRIMARY KEY (id)
);

ALTER TABLE businesses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME businesses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE INDEX ix_businesses_provider_id ON businesses (provider_id);

CREATE TABLE offers (
    id bigint NOT NULL,
    business_id bigint NOT NULL,
    title varchar(255) NOT NULL,
    category varchar(255) NOT NULL,
    zone varchar(255),
    description varchar(1000),
    discount_text varchar(255),
    valid_from timestamp(6) with time zone,
    valid_until timestamp(6) with time zone,
    photo_url varchar(255),
    status varchar(20) NOT NULL,
    origin varchar(50) NOT NULL,
    source_message_raw varchar(2000),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT offers_pkey PRIMARY KEY (id)
);

ALTER TABLE offers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME offers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE INDEX ix_offers_business_id ON offers (business_id);
CREATE INDEX ix_offers_status ON offers (status);
