-- Ruta comercio del CTA de interacción en ofertas (FIXY_OFERTAS_CTA_DESIGN.md
-- §4): mini-form determinista de consulta, sin pasar por el pipeline de
-- Lead — semántica distinta (mensaje de contacto completo, no un pedido de
-- servicio con datos faltantes).
--
-- business_id denormalizado a propósito (evita join para el admin, mismo
-- criterio que sourceName/sourceUrl en Offer). status string plano
-- ("NEW"/"FORWARDED"), mismo patrón que Offer.origin — dos estados alcanzan
-- al volumen de Fase 1, sin ciclo de vida más rico.

CREATE TABLE offer_inquiries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  offer_id bigint NOT NULL,
  business_id bigint NOT NULL,
  name varchar(100) NOT NULL,
  whatsapp_number varchar(100) NOT NULL,
  message varchar(500) NOT NULL,
  status varchar(20) NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE INDEX idx_offer_inquiries_offer_id ON offer_inquiries (offer_id);
