


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

-- Name: lead_events; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.lead_events (
    id bigint NOT NULL,
    actor character varying(80) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    message character varying(4000) NOT NULL,
    type character varying(80) NOT NULL,
    lead_id bigint NOT NULL
);


-- Name: lead_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.lead_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lead_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: lead_messages; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.lead_messages (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    lead_id bigint NOT NULL,
    sender character varying(16) NOT NULL,
    text character varying(2000) NOT NULL
);


-- Name: lead_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.lead_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lead_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: leads; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.leads (
    id bigint NOT NULL,
    assigned_provider character varying(255),
    channel character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    detected_category character varying(255),
    history character varying(12000),
    location character varying(255),
    missing_fields character varying(2000),
    name character varying(255),
    notes character varying(4000),
    phone character varying(255),
    problem character varying(2000) NOT NULL,
    ready_for_matching boolean NOT NULL,
    status character varying(255) NOT NULL,
    summary character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    urgency character varying(255),
    access_token character varying(64),
    assigned_provider_id bigint,
    CONSTRAINT leads_status_check CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'IN_REVIEW'::character varying, 'PROVIDER_CONTACTED'::character varying, 'ASSIGNED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


-- Name: leads_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.leads ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: provider_leads; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.provider_leads (
    id bigint NOT NULL,
    category character varying(255),
    channel character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    message character varying(2000) NOT NULL,
    missing_fields character varying(3000),
    name character varying(255),
    notes character varying(4000),
    phone character varying(255),
    ready_for_review boolean NOT NULL,
    status character varying(255) NOT NULL,
    summary character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    urgency character varying(255),
    zone character varying(255),
    CONSTRAINT provider_leads_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING_REVIEW'::character varying, 'READY_FOR_REVIEW'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


-- Name: provider_leads_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.provider_leads ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.provider_leads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: providers; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.providers (
    id bigint NOT NULL,
    accepted_jobs_count integer,
    categories character varying(255) NOT NULL,
    category_notes character varying(2000),
    city character varying(255),
    completed_jobs_count integer,
    coverage_zones character varying(1000),
    created_at timestamp(6) with time zone NOT NULL,
    department character varying(255),
    internal_score integer,
    last_contacted_at timestamp(6) with time zone,
    last_responded_at timestamp(6) with time zone,
    name character varying(255) NOT NULL,
    notes character varying(4000),
    phone character varying(255) NOT NULL,
    primary_zone character varying(255),
    rating_average double precision,
    rating_count integer,
    rejected_jobs_count integer,
    risk_flags character varying(1000),
    source_name character varying(255),
    source_type character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    verification_status character varying(255) NOT NULL,
    whatsapp_number character varying(255),
    access_token character varying(64),
    CONSTRAINT providers_status_check CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'CONTACT_PENDING'::character varying, 'CONTACTED'::character varying, 'RESPONDED'::character varying, 'AVAILABLE'::character varying, 'UNAVAILABLE'::character varying, 'REJECTED'::character varying, 'BLOCKED'::character varying, 'INACTIVE'::character varying])::text[]))),
    CONSTRAINT providers_verification_status_check CHECK (((verification_status)::text = ANY ((ARRAY['UNVERIFIED'::character varying, 'BASIC_CHECKED'::character varying, 'VERIFIED'::character varying])::text[])))
);


-- Name: providers_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.providers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.providers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: lead_events lead_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.lead_events
    ADD CONSTRAINT lead_events_pkey PRIMARY KEY (id);


-- Name: lead_messages lead_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.lead_messages
    ADD CONSTRAINT lead_messages_pkey PRIMARY KEY (id);


-- Name: leads leads_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.leads
    ADD CONSTRAINT leads_pkey PRIMARY KEY (id);


-- Name: provider_leads provider_leads_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.provider_leads
    ADD CONSTRAINT provider_leads_pkey PRIMARY KEY (id);


-- Name: providers providers_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.providers
    ADD CONSTRAINT providers_pkey PRIMARY KEY (id);


-- Name: ix_lead_messages_lead_id_created; Type: INDEX; Schema: public; Owner: -

CREATE INDEX ix_lead_messages_lead_id_created ON public.lead_messages USING btree (lead_id, created_at);


-- Name: lead_events fkh7g23x58canc78ymphlpmcwnd; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.lead_events
    ADD CONSTRAINT fkh7g23x58canc78ymphlpmcwnd FOREIGN KEY (lead_id) REFERENCES public.leads(id);




