-- Fase 1 de la ficha estructurada (gap analysis 2026-08-25, "mutación hacia
-- ficha estructurada + asistente WhatsApp + capa de agentes"): generaliza
-- Business de "nombre + una categoría + zona" a una ficha real que un motor
-- de respuesta pueda consultar. Tablas hijas normales, NO JSONB (decisión
-- del gap analysis §riesgos.3): el catálogo se filtra y se lista por
-- columnas indexadas, y dev/test corre H2 en modo PostgreSQL sin soporte
-- real de JSONB.
--
-- Igual que V19/V21/V23: válida para PostgreSQL (prod, flyway ON); en
-- dev/test flyway está OFF y ddl-auto=update cubre las entidades JPA — esta
-- migración no corre ahí pero se mantiene sincronizada.

-- description/categories: mismo criterio que V17 (nullable, sin backfill,
-- sin valor default) — la ferretería piloto y altas nuevas los llenan, los
-- comercios existentes quedan como estaban. categories es CSV en varchar,
-- mismo patrón que Provider.categories (no catálogo paralelo de rubros); el
-- campo `category` (singular) QUEDA por compatibilidad con lo que ya lee
-- OfferService.ingest y el resto del código existente.
ALTER TABLE businesses ADD COLUMN description varchar(500);
ALTER TABLE businesses ADD COLUMN categories varchar(500);

-- Catálogo de productos/marcas/rubros del comercio con nivel de confianza:
-- el corazón del plan ("¿tenés X?" contra la ficha). confidence distingue
-- lo que ops/el dueño declaró (DECLARADO), lo que ya se confirmó con una
-- consulta real resuelta (CONFIRMADO, con verified_at) y lo que Fixy infirió
-- sin confirmar todavía (INFERIDO) — ver BusinessCatalogItemService para la
-- regla de cuándo se estampa verified_at.
CREATE TABLE business_catalog_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL REFERENCES businesses(id),
  label varchar(120) NOT NULL,
  kind varchar(20) NOT NULL,
  price_from integer,
  confidence varchar(20) NOT NULL,
  verified_at timestamptz,
  notes varchar(500),
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE INDEX idx_business_catalog_items_business_id ON business_catalog_items (business_id);

-- Horarios del comercio: varias franjas por día permitidas a propósito (ej.
-- panadería con horario partido mediodía) — day_of_week es ISO (1=lunes,
-- 7=domingo), opens_at/closes_at texto "HH:mm" (no time real: alcanza para
-- mostrar/comparar, evita lidiar con zona horaria en un dato que siempre se
-- interpreta en hora local de Uruguay).
CREATE TABLE business_hours (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL REFERENCES businesses(id),
  day_of_week smallint NOT NULL,
  opens_at varchar(5) NOT NULL,
  closes_at varchar(5) NOT NULL,
  note varchar(200),
  created_at timestamptz NOT NULL
);

CREATE INDEX idx_business_hours_business_id ON business_hours (business_id);

-- Timeline append-only de la ficha, espejo exacto de lead_events (V1
-- baseline): cada mutación (update de datos, alta/baja/edición de catálogo,
-- reemplazo de horarios) queda un evento legible, nunca se actualiza ni se
-- borra. business_id denormalizado SIN FK a propósito — mismo criterio que
-- offer_inquiries.business_id (V19): evita joins para el admin y no hay
-- ciclo de vida propio que dependa de integridad referencial estricta acá.
CREATE TABLE business_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL,
  type varchar(80) NOT NULL,
  actor varchar(80) NOT NULL,
  message varchar(4000) NOT NULL,
  created_at timestamptz NOT NULL
);

CREATE INDEX idx_business_events_business_id ON business_events (business_id);
