-- Fase 2 de la mutación hacia ficha estructurada (gap analysis 2026-08-25):
-- motor de respuesta determinista sobre el catálogo con escalado al dueño.
-- Igual que V19-V24: válida para PostgreSQL (prod, flyway ON); en dev/test
-- flyway está OFF y ddl-auto=update cubre las entidades JPA — esta
-- migración no corre ahí pero se mantiene sincronizada.

-- "No tengo X" es una señal tan valiosa como "sí tengo X" (CatalogAnswerService):
-- un ítem CONFIRMADO con available=false le evita al vecino escribir por algo
-- que el comercio ya no vende, y evita que el motor le mienta que sí lo tiene
-- solo porque el label matcheó la pregunta.
ALTER TABLE business_catalog_items ADD COLUMN available boolean NOT NULL DEFAULT true;

-- Consulta de un vecino contra el catálogo de la ficha (CatalogAnswerService),
-- con escalado al dueño cuando el motor no tiene confianza suficiente
-- (BusinessInquiryService). business_id SIN FK a propósito — mismo patrón
-- que offer_inquiries (V19): evita joins para el panel/admin y no hay ciclo
-- de vida propio que dependa de integridad referencial estricta acá.
-- access_token (SecureRandom, 32 bytes → 43 chars base64url, mismo esquema
-- que businesses.panel_token) es la credencial del vecino para volver a ver
-- su respuesta sin login (GET /api/public/inquiries/{id}?token=).
CREATE TABLE business_inquiries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL,
  offer_id bigint,
  question varchar(500) NOT NULL,
  status varchar(30) NOT NULL,
  answer varchar(10),
  answer_note varchar(300),
  answer_source varchar(20),
  catalog_item_id bigint,
  visitor_name varchar(80),
  visitor_whatsapp varchar(30),
  access_token varchar(64) NOT NULL UNIQUE,
  push_endpoint varchar(500),
  created_at timestamptz NOT NULL,
  answered_at timestamptz,
  owner_notified_at timestamptz
);

CREATE INDEX idx_business_inquiries_business_id ON business_inquiries (business_id);
CREATE INDEX idx_business_inquiries_status ON business_inquiries (status);
