-- Refundación de Fixy, fase 1 (contrato REFUNDACION_FASE1_CONTRATO.md §2/§3,
-- 2026-09-14): catálogo de servicios con precio cerrado + columnas nuevas en
-- `leads` para el pedido estructurado. Mismo criterio que V24 (tabla nueva
-- sin JSONB: dev/test corre H2 en modo PostgreSQL sin soporte real) y que
-- V18/V27 (ALTER ... ADD COLUMN IF NOT EXISTS: prod es Flyway con
-- ddl-auto=validate, todo cambio de esquema entra por acá, nunca a mano). En
-- dev/test flyway está OFF y ddl-auto=update cubre las entidades JPA — esta
-- migración no corre ahí pero se mantiene sincronizada con
-- ServiceCatalogItem y Lead (y por lo tanto SIN datos semilla en dev/test:
-- los tests que necesiten un service_catalog cargado lo insertan ellos
-- mismos, mismo patrón que el resto de la suite).

CREATE TABLE IF NOT EXISTS service_catalog (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category varchar(64) NOT NULL,
  code varchar(64) NOT NULL,
  name varchar(120) NOT NULL,
  description varchar(300),
  price_from integer NOT NULL,
  price_to integer,
  duration_min integer,
  active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_service_catalog_code ON service_catalog (code);

-- Pedido estructurado (contrato §3): service_code referencia
-- service_catalog.code — sin FK a propósito, mismo criterio que
-- Lead.sourceOfferId/assignedProviderId (plain valor, sin @ManyToOne).
-- on_site_contact_* en dos columnas planas, no JSON: el contrato sugería
-- JSON/texto pero acá no hace falta consultarlo por campo ni filtrarlo —
-- dos varchar simples alcanzan y evitan una capa de (de)serialización sin
-- uso real (ver "Cambios durante implementación" al final del contrato).
ALTER TABLE leads ADD COLUMN IF NOT EXISTS service_code varchar(64);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS time_window varchar(32);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS remote boolean NOT NULL DEFAULT false;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS on_site_contact_name varchar(200);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS on_site_contact_phone varchar(60);

-- Semilla (contrato §2): precios orientativos de la zona (estudio
-- jul-2026), editables desde el admin (/api/services) sin volver a tocar
-- esta migración.
INSERT INTO service_catalog (category, code, name, description, price_from, price_to, duration_min, active, sort_order, created_at, updated_at) VALUES
  ('aires_acondicionados', 'aire_service', 'Service de split (limpieza y control)', 'Limpieza completa, control de gas y funcionamiento', 2900, NULL, NULL, true, 0, now(), now()),
  ('aires_acondicionados', 'aire_diagnostico', 'Diagnóstico: no enfría, no calienta, gotea', 'Se descuenta del arreglo si lo hacés con el mismo técnico', 900, NULL, NULL, true, 1, now(), now()),
  ('aires_acondicionados', 'aire_carga_gas', 'Carga de gas', 'Incluye control de pérdidas', 2500, 3500, NULL, true, 2, now(), now()),
  ('aires_acondicionados', 'aire_instalacion', 'Instalación de split', 'Equipo no incluido; hasta 3 m de cañería', 4900, 7500, NULL, true, 3, now(), now()),
  ('plomeria', 'plo_visita', 'Visita y diagnóstico de plomería', 'Se descuenta si hacés el arreglo', 700, NULL, NULL, true, 0, now(), now()),
  ('plomeria', 'plo_destape', 'Destape de pileta, inodoro o cañería', NULL, 1900, 3200, NULL, true, 1, now(), now()),
  ('plomeria', 'plo_perdida', 'Pérdida de canilla, cisterna o caño', 'Repuestos aparte', 1200, 2500, NULL, true, 2, now(), now()),
  ('plomeria', 'plo_calefon', 'Calefón: arreglo o cambio', 'Equipo no incluido', 1800, 3500, NULL, true, 3, now(), now()),
  ('barometrica', 'bar_pozo', 'Vaciado de pozo negro (barométrica)', 'Hasta 10.000 litros', 3200, 4500, NULL, true, 0, now(), now()),
  ('barometrica', 'bar_camara', 'Limpieza de cámara séptica', NULL, 3500, 5000, NULL, true, 1, now(), now());
