-- Refundación de Fixy, fase 2 (contrato REFUNDACION_FASE2_CONTRATO.md,
-- 2026-09-15): cargo de servicio al cliente (A) + casa a distancia (B).
-- Mismo criterio que V28: tabla nueva sin JSONB (dev/test corre H2 en modo
-- PostgreSQL sin soporte real), ALTER ... ADD COLUMN IF NOT EXISTS para las
-- columnas nuevas en tablas existentes (prod es Flyway con
-- ddl-auto=validate, todo cambio de esquema entra por acá). En dev/test
-- flyway está OFF y ddl-auto=update cubre las entidades JPA — esta
-- migración no corre ahí pero se mantiene sincronizada con CustomerPayment,
-- RemoteCarePlan, LeadRating y Lead (sin datos semilla salvo el servicio
-- de precio 0 de la visita preventiva, que si hace falta en prod real).

-- A.3: cargo de servicio al cliente + plan mensual de casa a distancia,
-- misma tabla (kind discrimina) por contrato.
CREATE TABLE IF NOT EXISTS customer_payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind varchar(24) NOT NULL,
  lead_id bigint,
  remote_care_plan_id bigint,
  customer_name varchar(200),
  customer_phone varchar(60),
  base_amount numeric(12,2),
  fee_percent numeric(5,2),
  amount numeric(12,2) NOT NULL,
  currency varchar(8) NOT NULL DEFAULT 'UYU',
  status varchar(16) NOT NULL,
  mp_preference_id varchar(100),
  mp_payment_id varchar(100),
  mp_payment_link varchar(500),
  created_at timestamptz NOT NULL,
  paid_at timestamptz,
  reminded_at timestamptz,
  guarantee_until timestamptz
);

CREATE INDEX IF NOT EXISTS ix_customer_payments_status ON customer_payments (status);
CREATE INDEX IF NOT EXISTS ix_customer_payments_lead_id ON customer_payments (lead_id);
CREATE INDEX IF NOT EXISTS ix_customer_payments_remote_care_plan_id ON customer_payments (remote_care_plan_id);

-- B.2: planes de casa a distancia.
CREATE TABLE IF NOT EXISTS remote_care_plans (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_name varchar(200) NOT NULL,
  owner_phone varchar(60) NOT NULL,
  owner_email varchar(200),
  property_zone varchar(100) NOT NULL,
  property_address varchar(255) NOT NULL,
  on_site_name varchar(200),
  on_site_phone varchar(60),
  notes varchar(1000),
  monthly_price integer NOT NULL,
  status varchar(16) NOT NULL,
  access_token varchar(64) NOT NULL,
  created_at timestamptz NOT NULL,
  activated_at timestamptz,
  last_billed_at timestamptz,
  next_visit_note varchar(500)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_remote_care_plans_access_token ON remote_care_plans (access_token);
CREATE INDEX IF NOT EXISTS ix_remote_care_plans_status ON remote_care_plans (status);

-- A.4.4: sello de reseña verificada — solo los trabajos con cargo de
-- servicio pagado marcan la reseña como verificada.
ALTER TABLE lead_ratings ADD COLUMN IF NOT EXISTS verified boolean NOT NULL DEFAULT false;

-- B: pedidos remotos originados en un plan de casa a distancia.
ALTER TABLE leads ADD COLUMN IF NOT EXISTS remote_care_plan_id bigint;

-- B.3, nota: visita preventiva de precio 0 (no genera cargo de servicio al
-- cliente — amount 0 no crea CustomerPayment, ver CustomerPaymentService).
INSERT INTO service_catalog (category, code, name, description, price_from, price_to, duration_min, active, sort_order, created_at, updated_at)
SELECT 'plomeria', 'care_visita', 'Visita preventiva del plan Casa a distancia', 'Incluida en el plan mensual, sin costo adicional', 0, NULL, NULL, true, 99, now(), now()
WHERE NOT EXISTS (SELECT 1 FROM service_catalog WHERE code = 'care_visita');
