-- P0-1: comisión de Fixy sobre leads COMPLETED (Mercado Pago).
--
-- Válida para PostgreSQL (prod, flyway ON) e H2 en modo PostgreSQL (dev,
-- flyway OFF, ddl-auto=update ya cubre la entidad JPA — esta migración no
-- corre en dev pero se mantiene compatible con H2 por si se necesita en
-- algún entorno con flyway habilitado).

CREATE TABLE lead_payments (
    id bigint NOT NULL,
    lead_id bigint NOT NULL,
    provider_id bigint NOT NULL,
    amount_charged numeric(12,2) NOT NULL,
    commission_rate numeric(5,4) NOT NULL,
    commission_amount numeric(12,2) NOT NULL,
    currency varchar(8) NOT NULL,
    commission_status varchar(20) NOT NULL,
    mp_preference_id varchar(100),
    mp_payment_id varchar(100),
    mp_payment_link varchar(500),
    created_at timestamp(6) with time zone NOT NULL,
    paid_at timestamp(6) with time zone,
    CONSTRAINT lead_payments_pkey PRIMARY KEY (id),
    CONSTRAINT lead_payments_commission_status_check CHECK (
        (commission_status)::text = ANY (
            (ARRAY['PENDING', 'PAID', 'WAIVED', 'OVERDUE']::character varying[])::text[]
        )
    )
);

ALTER TABLE lead_payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lead_payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE INDEX ix_lead_payments_commission_status ON lead_payments (commission_status);
CREATE INDEX ix_lead_payments_provider_id ON lead_payments (provider_id);
