-- P0-2: loop de cierre — confirmación de trabajo + rating (H2.1-H2.6).
--
-- Igual que V2: válida para Postgres (prod, flyway ON) y compatible con H2
-- en modo PostgreSQL; en dev/test flyway está OFF y ddl-auto=update cubre
-- las entidades JPA — esta migración no corre ahí pero se mantiene
-- sincronizada por si se habilita flyway en algún entorno.

CREATE TABLE lead_ratings (
    id bigint NOT NULL,
    lead_id bigint NOT NULL,
    provider_id bigint NOT NULL,
    score integer NOT NULL,
    comment varchar(1000),
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT lead_ratings_pkey PRIMARY KEY (id),
    CONSTRAINT uq_lead_ratings_lead_id UNIQUE (lead_id),
    CONSTRAINT lead_ratings_score_check CHECK (score BETWEEN 1 AND 5)
);

ALTER TABLE lead_ratings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lead_ratings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE INDEX ix_lead_ratings_provider_id ON lead_ratings (provider_id);

-- H2.6: flag de disputa cuando el cliente reporta que el trabajo no se hizo
-- o hubo un problema al confirmar completado. Columna en Lead (no un nuevo
-- LeadStatus) porque no reemplaza el status real del lead (sigue
-- COMPLETED): es una señal ortogonal para la cola de ops, y así no se
-- rompen las transiciones existentes de LeadStatus.
ALTER TABLE leads ADD COLUMN disputed boolean NOT NULL DEFAULT false;

-- H2.4: timestamp de auto-confirmación a las 72h. Nullable; se setea una
-- sola vez por el scheduler para garantizar idempotencia (si ya tiene
-- valor, no se re-emite el evento).
ALTER TABLE leads ADD COLUMN closing_auto_confirmed_at timestamp(6) with time zone;
