-- Bandeja de oportunidades del proveedor: registro de rechazos por
-- (lead, provider) para que una oportunidad rechazada no le vuelva a
-- aparecer a ESE proveedor (a otros proveedores que matcheen, sí).
--
-- Igual que V2/V3: válida para PostgreSQL (prod, flyway ON) y compatible
-- con H2 en modo PostgreSQL; en dev/test flyway está OFF y ddl-auto=update
-- cubre la entidad JPA — esta migración no corre ahí pero se mantiene
-- sincronizada por si se habilita flyway en algún entorno.

CREATE TABLE provider_lead_declines (
    id bigint NOT NULL,
    lead_id bigint NOT NULL,
    provider_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT provider_lead_declines_pkey PRIMARY KEY (id),
    CONSTRAINT uq_provider_lead_declines_lead_provider UNIQUE (lead_id, provider_id)
);

ALTER TABLE provider_lead_declines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME provider_lead_declines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE INDEX ix_provider_lead_declines_provider_id ON provider_lead_declines (provider_id);
