-- Google Sign-In opcional y post-valor: identidad persistente cross-device
-- y vínculo de leads que el cliente ya generó como anónimo (posee el
-- accessToken en localStorage). No reemplaza el chat anónimo por
-- accessToken, que sigue siendo el flujo principal de conversión.
--
-- Igual que V2/V3/V4: válida para PostgreSQL (prod, flyway ON) y compatible
-- con H2 en modo PostgreSQL; en dev/test flyway está OFF y ddl-auto=update
-- cubre la entidad JPA — esta migración no corre ahí pero se mantiene
-- sincronizada por si se habilita flyway en algún entorno.

CREATE TABLE users (
    id bigint NOT NULL,
    google_sub varchar(255) NOT NULL,
    email varchar(255),
    name varchar(255),
    picture_url varchar(1000),
    created_at timestamp(6) with time zone NOT NULL,
    last_login_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uq_users_google_sub UNIQUE (google_sub)
);

ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE user_leads (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    lead_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT user_leads_pkey PRIMARY KEY (id),
    CONSTRAINT uq_user_leads_user_lead UNIQUE (user_id, lead_id)
);

ALTER TABLE user_leads ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME user_leads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE INDEX ix_user_leads_user_id ON user_leads (user_id);
