-- Web Push (Ola UX): suscripciones del navegador para avisar a cliente y
-- proveedor aunque la pestaña esté cerrada. Una fila por dispositivo/
-- navegador suscripto; pertenece a un lead (cliente) O a un provider
-- (proveedor), nunca a ambos.
--
-- Igual que V4: válida para PostgreSQL (prod, flyway ON); en dev/test
-- flyway está OFF y ddl-auto=update cubre la entidad JPA — esta migración
-- no corre ahí pero se mantiene sincronizada.

CREATE TABLE push_subscriptions (
    id bigint NOT NULL,
    lead_id bigint,
    provider_id bigint,
    endpoint varchar(2000) NOT NULL,
    p256dh varchar(200) NOT NULL,
    auth varchar(200) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT push_subscriptions_pkey PRIMARY KEY (id)
);

ALTER TABLE push_subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME push_subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE INDEX ix_push_subscriptions_lead_id ON push_subscriptions (lead_id);
CREATE INDEX ix_push_subscriptions_provider_id ON push_subscriptions (provider_id);
